# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Imandra Inc. Documentation
email: contact@imandra.ai
description: >- # this means to ignore newlines until "baseurl:"
  Documentation on all products and services provided by Imandra Inc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.imandra.ai" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: VerifiedbyAI
github_username: AestheticIntegration
permalink: /:title/

# Build settings
layouts_dir: jekyll-resources/_layouts
includes_dir: jekyll-resources/_includes
data_dir: jekyll-resources/_data
plugins_dir: jekyll-resources/_plugins
sass:
  sass_dir: jekyll-resources/_sass
kramdown:
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - wercker.yml
  - README.md
  - README.public.md

#theme: jekyll-theme-slate

collections:
  technology:
    output: true
    sequence: 1
  products:
    output: true
    sequence: 0
  models:
    output: true
    sequence: 2
